spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Start#123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

websiteUrl: http://localhost:3000/


    


