spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Start#123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTockenExpiration: 7200 #5m 
    refreshTockenExpiration: 604800 #7d
stripe:
    secretKey: ${STRIPE_KEY}
websiteUrl: http://localhost:4242
    


